### ISSUE TITLE
Keyring implementation for Near protocol chain account management

### ISSUE THREAD

**Issue by ARJUN-R34** [getsafle/vault-aurora-controller#1]
Implement Keyring functionality to manage multiple near protocol account keypairs.

This package should include methods to generate accounts, export keys, sign transactions, broadcast transactions and get the network transaction fees

**Comment by surajsingla333** [comment]
NEAR protocol is not EVM compatible. ETH like addresses does not work on NEAR and nor does the web3 integration works. They have their own package and APIs to deploy smart contracts and blockchain integration.

AURORA is an EVM compatible chain built on NEAR and thus we need to update the near-controller to aurora controller.
